### ISSUE TITLE
lib not found after fresh install

### ISSUE THREAD

**Issue by joaomcteixeira** [MDAnalysis/mdacli#26]
with MDAnalysis 1.1.1

```
(mdacli) joao@vantito:~/github/mda_cli
· mdacli 
Traceback (most recent call last):
  File "/home/joao/anaconda3/envs/mdacli/bin/mdacli", line 33, in <module>
    sys.exit(load_entry_point('mdacli', 'console_scripts', 'mdacli')())
  File "/home/joao/github/mda_cli/src/mdacli/cli.py", line 591, in main
    maincli(setup_clients())
  File "/home/joao/github/mda_cli/src/mdacli/cli.py", line 575, in setup_clients
    module = importlib.import_module('MDAnalysis.analysis.' + module)
  File "/home/joao/anaconda3/envs/mdacli/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'MDAnalysis.analysis.rdf_s'
```

**Comment by joaomcteixeira** [comment]
Works well in MDA v2. sorry
